- hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Remove old container
      command: docker rm -f app
      ignore_errors: yes

    - name: Run container
      command: docker run -d -p 8081:80 --name app 472004/poc7-app
